# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-04 01:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(default='xxx-xxxx', max_length=20)),
                ('renavan', models.CharField(max_length=20)),
                ('marca', models.CharField(max_length=20)),
                ('modelo', models.CharField(max_length=20)),
                ('ano', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'Carros',
                'verbose_name': 'Carro',
            },
        ),
        migrations.CreateModel(
            name='Esposa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=20)),
                ('casamento_data', models.DateField(verbose_name='Certidao_de_Casamento')),
                ('cpf', models.CharField(max_length=11, unique=True, verbose_name='CPF')),
                ('rg', models.CharField(max_length=20)),
                ('data_de_exp', models.DateField(verbose_name='Data_de_Exp')),
                ('titulo_eleitor', models.CharField(max_length=20)),
                ('passaporte', models.CharField(blank=True, max_length=20)),
                ('nacionalidade', models.CharField(blank=True, max_length=20)),
                ('naturalidade', models.CharField(blank=True, max_length=20)),
                ('formacao', models.CharField(blank=True, max_length=20)),
                ('proficao', models.CharField(max_length=20)),
                ('indioma', models.CharField(blank=True, max_length=10)),
                ('tempo_de_evangelho', models.CharField(blank=True, max_length=10)),
            ],
            options={
                'verbose_name_plural': 'Esposas',
                'verbose_name': 'Esposa',
            },
        ),
        migrations.CreateModel(
            name='Filho',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('data_de_nascimento', models.DateField(verbose_name='Data_de_Nascimento')),
            ],
            options={
                'verbose_name_plural': 'Filhos',
                'verbose_name': 'Filho',
            },
        ),
        migrations.CreateModel(
            name='Igreja',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('IURD', models.CharField(blank=True, choices=[('barao', 'BARAO'), ('lorival', 'LORIVAL'), ('sede', 's')], max_length=10)),
                ('bairro', models.CharField(blank=True, max_length=15)),
                ('cep', models.CharField(blank=True, max_length=15)),
                ('cidade', models.CharField(blank=True, max_length=15)),
                ('cnpj', models.CharField(blank=True, max_length=15)),
                ('contato', models.CharField(blank=True, max_length=15)),
                ('email', models.CharField(blank=True, max_length=15)),
                ('endereco', models.CharField(blank=True, max_length=15)),
                ('numero', models.CharField(max_length=15)),
                ('possui_carro', models.BooleanField(default=True)),
                ('telefone', models.CharField(blank=True, max_length=15)),
                ('carro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Carro')),
            ],
            options={
                'verbose_name_plural': 'Igrejas',
                'verbose_name': 'Igreja',
            },
        ),
        migrations.CreateModel(
            name='Pastor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30, verbose_name='Nome')),
                ('estado_civil', models.CharField(choices=[('C', 'CASADO'), ('D', 'DIRVOCIADO'), ('S', 'SOLTEIRO'), ('V', 'VIUVO')], max_length=10)),
                ('pastor_regional', models.BooleanField(default=False)),
                ('data_de_nascimento', models.DateField(verbose_name='Data_de_Nascimento')),
                ('cpf', models.CharField(blank=True, max_length=20, verbose_name='Cpf')),
                ('rg', models.CharField(max_length=20)),
                ('data_de_exp', models.DateField(verbose_name='Data_de_Exp')),
                ('cnh', models.CharField(max_length=20)),
                ('regiao', models.CharField(choices=[('barao', 'BARAO'), ('lorival', 'LORIVAL'), ('sede', 's')], max_length=10)),
                ('titulo_eleitor', models.CharField(max_length=20)),
                ('zona', models.CharField(max_length=10)),
                ('seção', models.CharField(max_length=20)),
                ('passaporte', models.CharField(max_length=15)),
                ('nacionalidade', models.CharField(blank=True, max_length=20)),
                ('naturalidada_uf', models.CharField(blank=True, max_length=20)),
                ('grau_de_instrução', models.CharField(blank=True, choices=[('1°', '1°Grau'), ('2°', '2°Grau'), ('S', 'Superior')], max_length=30)),
                ('proficao', models.CharField(blank=True, max_length=20)),
                ('indioma', models.CharField(max_length=10)),
                ('telefone', models.CharField(max_length=10)),
                ('celula', models.CharField(default='', max_length=20)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('whatsapp', models.CharField(blank=True, max_length=10)),
                ('pastor', models.CharField(blank=True, choices=[('Aux', 'Auxiliar'), ('Pr', 'Pr.Titular'), ('Bp', ' Bispo')], max_length=20)),
                ('esposa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Esposa')),
            ],
            options={
                'verbose_name_plural': 'Pastores',
                'verbose_name': 'Pastor',
            },
        ),
    ]
